### ISSUE TITLE
Manticoil bodies

### ISSUE THREAD

**Issue by Stratdan** [Entity378/LC-SellBodiesFixed#1]
Hey! I was messing around with the mod and killed a manticoil. 

(These birds)
![image](https://github.com/Entity378/LC-SellBodiesFixed/assets/85818065/d238bac6-8a7c-41c3-ac95-3c7cf65b83de) 
![image](https://github.com/Entity378/LC-SellBodiesFixed/assets/85818065/92811b70-890b-4d4f-95e3-b2f10f7c49d9)

And instead of getting the body like expected, i got common enemy remains, which i think is the drop from modded enemies.
![image](https://github.com/Entity378/LC-SellBodiesFixed/assets/85818065/5d6f8d81-f56a-4733-9ea9-d5917d28b6db)

Would be nicer if i could hold the bird

**Comment by Entity378** [comment]
> Hey! I was messing around with the mod and killed a manticoil.
> 
> (These birds) ![image](https://private-user-images.githubusercontent.com/85818065/316558227-d238bac6-8a7c-41c3-ac95-3c7cf65b83de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODU0NTAsIm5iZiI6MTcxMTM4NTE1MCwicGF0aCI6Ii84NTgxODA2NS8zMTY1NTgyMjctZDIzOGJhYzYtOGE3Yy00MWMzLWFjOTUtM2M3Y2Y2NWI4M2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE2NDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NmJiNDQ3MDA3NzliODU2YmI5NTljOTVhNGNjNTZkNjdlZjI3NzMxYzlkNjJhNWZhZTgxODk2M2FlNTAwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xBWcuM7-KXzdwOcBeunWb1G9kv_D1u9ggQgONxWk5I0) ![image](https://private-user-images.githubusercontent.com/85818065/316559344-92811b70-890b-4d4f-95e3-b2f10f7c49d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODU0NTAsIm5iZiI6MTcxMTM4NTE1MCwicGF0aCI6Ii84NTgxODA2NS8zMTY1NTkzNDQtOTI4MTFiNzAtODkwYi00ZDRmLTk1ZTMtYjJmMTBmN2M0OWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE2NDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNDUzOGY1Nzg0ZDBlYjMzMDZjMTgwMDk0YTc1YjNhZmMwMmIwZTgyNTVmYzUwNzJhYjZmNWIxNjVmNjVmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AyQw7__vmIw0e4vdfXrHwOU_qZjPXd51FeUTxmdolsM)
> 
> And instead of getting the body like expected, i got common enemy remains, which i think is the drop from modded enemies. ![image](https://private-user-images.githubusercontent.com/85818065/316557649-5d6f8d81-f56a-4733-9ea9-d5917d28b6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODU0NTAsIm5iZiI6MTcxMTM4NTE1MCwicGF0aCI6Ii84NTgxODA2NS8zMTY1NTc2NDktNWQ2ZjhkODEtZjU2YS00NzMzLTllYTktZDU5MTdkMjhiNmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE2NDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZjliODEzOGUxODUyMTlhYTBhNThhNjViYmJkNTg1YjFlYmI2YjJhMTE1NjlmOWYxODE4NDhiYjQzMmZjYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fsbKMuZsZFPZOomXr5RxyPf_uf_fKacPiJS3fFcBxV0)
> 
> Would be nicer if i could hold the bird
Yes, that is one of the 3 drops of the modded monsters (the one that is worth the least to be precise).
To be honest, I had completely forgotten about the existence of Manticoils and therefore I forgot to put them in the filter that manages whether the mob is vanilla or not. Honestly, I didn't have the goal of making the Manticoils drop anything, but at this point I think it's worth adding them among the droppable bodies, even if I don't think I'll make them count too much.

**Comment by Entity378** [comment]
The Manticoil body was added with the version 1.7.0 of the mod.
