### ISSUE TITLE
Make Masked Enemies Sellable

### ISSUE THREAD

**Issue by FlySlime** [Entity378/LC-SellBodiesFixed#15]
See title, would be neat! Maybe as an option in the config file at least?

**Comment by Entity378** [comment]
After doing some updates to all my mods i'm back to taking a break from modding LC. When i get back to modding lethal i think the masked drop will be the first thing i'll add to the mod due to high demand.

**Comment by Entity378** [comment]
Masked now drop their corresponding mask when killed. There are currently no options to change the mask value or mask weight, only to enable/disable the drop.
