### ISSUE TITLE
[Request] (For LETHAL DOORS FIXED)

### ISSUE THREAD

**Issue by MathiusXII** [Entity378/LC-SellBodiesFixed#4]
You don't have a github page linked for Lethal Doors Fixed, so I'll try to contact you here...

Could you make powered doors in the facility lethal too?

**Comment by Entity378** [comment]
I've never created a github page for lethal doors, however I think it would be too complicated to make the doors in the facility "lethal" since ship doors and facility doors work in completely different ways.
