### ISSUE TITLE
mod desync with other users

### ISSUE THREAD

**Issue by RecklessBravery** [Entity378/LC-SellBodiesFixed#5]
When i enter the game and i kill monsters normally, so do the other clients, however, they cant see the bodies nor pick them up expect the host. is there any solution?

**Comment by Entity378** [comment]
I would like to know what version of the game you were playing and it would also be appreciated if you sent me the server logs and at least one of the client otherwise I can't understand if the problem comes directly from my mod or is caused by some conflict.
