### ISSUE TITLE
Confetti and audio on enemy death

### ISSUE THREAD

**Issue by TerabyteTim** [Entity378/LC-SellBodiesFixed#6]
With this mod added, when I kill enemies they explode with confetti and a “party” noise of cheering. Removing the mod fixes this.

I can’t find any config value anywhere to disable this. Is this a bug?

**Comment by BartBlaak** [comment]
The author added the confetti in the latest version (v1.9.4) to celebrate one million downloads. To remove the confetti, you can uninstall the mod and re-install the previous version (v.9.3).

**Comment by Entity378** [comment]
I added confetti in the latest version to celebrate the 1M downloads of the mod. If you want to remove the confetti just downgrade the mod.

**Comment by TerabyteTim** [comment]
Will all future versions contain this confetti as well?

Just asking to see if I should update in the future, or lock to previous version.

It’s super buggy in the latest version; confetti particles go off at random all the time

**Comment by Entity378** [comment]
in future versions it will be configurable and will be set to false by default. However the confetti do not go "random". if you kill the enemy then the confetti go off, if it happens in other occasions it means that there is some other mod that calls the function to kill the enemies (it is not my problem)

**Comment by TerabyteTim** [comment]
Yeah we’re seeing bursts of confetti with no enemies around. Happens outdoors as well. Will downgrade for now and wait for the bug fix, thanks!

**Comment by Entity378** [comment]
> Yeah we’re seeing bursts of confetti with no enemies around. Happens outdoors as well. Will downgrade for now and wait for the bug fix, thanks!

I wanted to inform you that a new update of the mod has been released that disables the confetti by default (you can re-enable them from the config if you want)
