### ISSUE TITLE
Drop for old bird ( the robot enemy ) Doesn't drop.

### ISSUE THREAD

**Issue by RenzKanade** [Entity378/LC-SellBodiesFixed#7]
I don't know if it was because another mod, or because what, but sometime when playing, I come across the item that seems to be dropped when defeating the Old Bird enemy. But lately the it doesn't drop.

**Comment by Entity378** [comment]
I accidentally broke the code with the latest update for all entities while trying to fix another issue, today I'm releasing an update to fix the issue

**Comment by RenzKanade** [comment]
Thank you very much for the response!
