### ISSUE TITLE
Body despawns a couple of seconds after the kill

### ISSUE THREAD

**Issue by DeCat4** [Entity378/LC-SellBodiesFixed#9]
When i kill any enemy (i tested with dogs too) their bodies despawn after a couple of seconds and i never get a pickup prompt, this is my first time using the mod so i'm not sure if i'm just doing smthn wrong

https://github.com/user-attachments/assets/8cc06e54-f4c1-49e0-8bef-9c6627b8b516

**Comment by AdverseMiller** [comment]
having same issue

**Comment by vazab** [comment]
Yes that's right, been using the mod for a long time and the bodies have now started disappearing after killing. It happens to all my friends. Need a fix.

**Comment by Entity378** [comment]
I accidentally broke the code with the latest update while trying to fix another issue, today I'm releasing an update to fix the issue
